#pragma config(Hubs,  S1, HTMotor,  HTServo,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     ir_seeker,      sensorHiTechnicIRSeeker600)
#pragma config(Motor,  mtr_S1_C1_1,     dt_left,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     dt_right,      tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Servo,  srvo_S1_C2_1,    servo1,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

const int TICKS_PER_ROTATION = 1440;
const int WHEEL_CIRCUM = 3;

const int target_inches = 12;
const int motor_speed = 60;
const int target_ticks = 15000;

void initializeRobot () {
	motor[dt_left] = 0;
	motor[dt_right] = 0;

	nMotorEncoder[dt_right] = 0;
}

int inchesToEncoder (float p_inches) {
	return p_inches * TICKS_PER_ROTATION / WHEEL_CIRCUM;
}

task main () {
	initializeRobot();

	motor[dt_left] = motor_speed;
	motor[dt_right] = motor_speed;

	while(abs(nMotorEncoder[dt_right]) < target_ticks) {
		writeDebugStreamLine("%d\t%d", nMotorEncoder[dt_right], target_ticks);
	}

	motor[dt_left] = 0;
	motor[dt_right] = 0;
}
